### ISSUE TITLE
Can't the contents of a group in a scene be displayed in Scene Items?

### ISSUE THREAD

**Issue by umbrella-k** [exeldro/obs-source-dock#13]
Can't the contents of a group in a scene be displayed in Scene Items?
Currently, even if the source is a Scene or a group within a Scene, the items within the group are not displayed.
Is it not possible to view within a group, like the regular source item dock in OBS?

**Comment by exeldro** [comment]
Support for groups is indeed something that is not added yet.

**Comment by exeldro** [comment]
I added it. It should be in the next version of the plugin. You can find a test build at the bottom of this page:
https://github.com/exeldro/obs-source-dock/actions/runs/12189280861
