### ISSUE TITLE
Help: Can this tool be set not to display milliseconds

### ISSUE THREAD

**Issue by gcyzidane** [exeldro/obs-source-dock#18]
Help: Can this tool be set not to display milliseconds, but only hours, minutes and seconds? For me, milliseconds are not needed. It is a bit annoying.

**Comment by exeldro** [comment]
that is something that can be added, but need to find a good way to configure it.

**Comment by exeldro** [comment]
I added it, you can enable it by right clicking it. You can download a test version when logged in on GitHub from the bottom of this page:
https://github.com/exeldro/obs-source-dock/actions/runs/8458533814
