### ISSUE TITLE
Docks are reordered/sorted after OBS Studio restarts

### ISSUE THREAD

**Issue by rse** [exeldro/obs-source-dock#2]
First, a very nice idea, the new "Source Dock" plugin ;-)

I've played around with version 0.1.0 and I've the following subtle issue. I add multiple sources (scenes actually for me) as docks to the right hand side of my OBS Studio instance. Once I restart OBS Studio the order of the docks are changed. It looks like they get added in the order of their sorted names? Check out the before and after screenshot of a two docks, one with two tabs situation:

<img width="840" alt="1" src="https://user-images.githubusercontent.com/221273/125169597-392f7200-e1ab-11eb-84fb-17fc20baca74.png">
<img width="843" alt="2" src="https://user-images.githubusercontent.com/221273/125169599-3c2a6280-e1ab-11eb-9185-5f2d342308b7.png">

And then here is a simpler scenario with the three scenes docked as separate docks:

<img width="839" alt="3" src="https://user-images.githubusercontent.com/221273/125169609-4a787e80-e1ab-11eb-858d-025138b8c721.png">
<img width="842" alt="4" src="https://user-images.githubusercontent.com/221273/125169611-4cdad880-e1ab-11eb-947a-7cb2df538df5.png">

In both cases, after OBS Studio restarted, the order of the docks get "sorted".

**Comment by exeldro** [comment]
that should be fixed with https://github.com/exeldro/obs-source-dock/commit/76b37f6ee840367a7e905450d7f780e8fe179f48
test version building here: https://github.com/exeldro/obs-source-dock/actions/runs/1018427045

**Comment by rse** [comment]
Ok, I tried the snapshot version and can confirm: it fixes the issue. The dock state now correctly restores. Thanks!
