### ISSUE TITLE
OBS V27.0.1 not support

### ISSUE THREAD

**Issue by kirahan** [exeldro/obs-source-dock#5]
install source dock on obs version 27.0.1, on the menubar can't find Tool->Source Dock

**Comment by exeldro** [comment]
Source dock requires OBS version 27.1 since version 0.1.4 of Source Dock

**Comment by kirahan** [comment]
ok, the description on OBS Forums 
The Minimum OBS Studio Version is still 27.0.0
https://obsproject.com/forum/resources/source-dock.1317/

**Comment by exeldro** [comment]
The OBS forum gives me a list of versions to choose from, 27.1 is not an option:
![image](https://user-images.githubusercontent.com/5457024/140870902-921c1701-76ab-4e97-961a-ac2391e170fb.png)

**Comment by kirahan** [comment]
lol
