### ISSUE TITLE
Interaction in case of a scene with a contained Browser Source

### ISSUE THREAD

**Issue by rse** [exeldro/obs-source-dock#6]
First, let me thank you for the great Source Dock plugin you created this year. I use it since a few months during my training for having a permanent preview of a source at hand independent of the OBS preview. Really handy! Many thanks, exceldro!

Currently I'm faced with a scenario which Source Dock still does not support, which other users also already mentioned in the forum and which I think could be possible for Source Dock. First, let me explain the scenario: you have a scene with a Browser Source (with a transparent background) on top of other Video Capture Device and more sources. In my cases, the Browser Source is a Head-Up-Display (HUD) or a PTZ Camera UI. The request is to be able to directly interact with the Browser Source once the entire scene (not just the Browser Source) is loaded into a Source Dock. 

The problem now is: if Source Dock contains just the Browser Source you can interact with it, but you are missing the information of the sources "optically behind" the Browser Source. If the Source Dock contains the entire scene (with the Browser Source), then one has the information of the sources "optically behind" the Browser Source available, but you no longer can interact with the Browser Source.

I can imagine three potential solutions:

1. I guess one cannot interact with the entire scene in the Source Dock because it is internally not flagged interactive. Perhaps Source Dock (or a different filter plugin) can provide a flag to "force" OBS to make the entire scene interactive and this way one can also interact with it in Source Dock.

2. Perhaps Source Dock can detect that its content is a scene with a Browser Source and somewhat "proxy" the interaction into it.

3. In case (1) and (2) fail, perhaps Source Dock could allow one to just optically stack multiple Source Dock instances over each other. This way one could create a Source Dock for the Browser Source and another Source Dock "behind" it with the remaining scene sources. This way the result is optically still the same: the transparent Browser Source on top of the content.

I guess option (1) and (2) could be not possible due to the OBS Studio internals. But option (3) perhaps is possible?

**Comment by exeldro** [comment]
What would you like to happen when you have multiple browser sources on a scene and you press a key or click on that scene?
Send it to all browser sources? Let typing/ keypresses only work when the cursor is on the browser source?
What if there are multiple browser sources behind each other?

**Comment by rse** [comment]
In case there are multiple browser sources behind each other we cannot know which one should receive the interaction, of course. The only possibility in this case might be to decide to just send the interaction just to the top/front browser source, as for interaction one needs the controls to be visible anyway. That would be just a heuristic, but I think it could be sufficient in practice. Sending the interaction to all browser sources could be a problem for at least typing, so I would avoid this approach of sending the interaction to multiple sources. For most scenarios of Source Dock based control UIs, one will have a single browser source anyway, I think.

**Comment by rse** [comment]
To have an even better understanding of my mentioned "PTZ Camera UI", I've now released my OBS-Crop-Control HTML5 SPA under https://github.com/rse/obs-crop-control. There you can see it in the browser and inside Source Dock. The preview functionality (when the eye icon is toggled, the video where the area is cropped is shown in the background) currently is based on just OBS WebSocket's `TakeSourceScreenshot` functionality. This works, but is a major performance nightmare and unusable in production, even with low preview-FPS. Instead of this `TakeSourceScreenshot` functionality, it would be cool if an arbitrary scene of OBS Studio could be placed just behind the Browser Source of OBS-Crop-Control in Source Dock. I hope this further illustrates what kind of overlay-based control applications I have in mind.

**Comment by exeldro** [comment]
I made a version:
https://github.com/exeldro/obs-source-dock/actions/runs/1646802600
To use it you must have the "switch scene" option disabled on the source dock of the scene
mouse events go to sources that are under the cursor
keyboard events go to all sources of that scene
groups are not supported

Can you test if this works like you want it?

**Comment by rse** [comment]
I've immediately tried it: PHANTASTIC, Exeldro! I've created a scene with a Browser Source running a UI control (with transparent background) on the top of the source list and added this scene to the Source Dock. Great, the entire scene is displayed correctly and I can even drag the UI controls inside this Source Dock. Perfect. For testing the keyboard events I fist have to change the UI control (it currently was written for just mouse dragging), but I'll check this one out in two hours, too.

**Comment by rse** [comment]
Ok, keyboard events also work just fine. Ultra cool. So, the intended functionality is there and works as expected!

**Comment by rse** [comment]
Ok, I've even more tested in depth and it works perfectly. I've not found any bug. See my resulting scenario in this screenshot:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/221273/147891022-c20775d2-4b96-4031-b6c9-a6727edbaaf0.png">

So, I would say: time to release this functionality with a new version of the plugin. Really well done. Excellent job, Exceldo!

**Comment by exeldro** [comment]
released with version 0.2.3
https://github.com/exeldro/obs-source-dock/releases/tag/0.2.3
