### ISSUE TITLE
Can Not Build Successfully in MacOS

### ISSUE THREAD

**Issue by jonahjunwu** [exeldro/obs-source-dock#8]
Hi,
I can not build the source-dock successfully.
 
I just follow the build instructions:
1. Build OBS Studio: https://obsproject.com/wiki/Install-Instructions
2. Check out this repository to UI/frontend-plugins/source-dock
3. Add add_subdirectory(source-dock) to UI/frontend-plugins/CMakeLists.txt
4. Rebuild OBS Studio

I can build OBS Studio Success, but after adding the source-dock,
I got the error result:

 ```
CMake Error at UI/frontend-plugins/source-dock/CMakeLists.txt:43 (target_link_libraries):
  Target "source-dock" links to:
Qt5::Widgets
but the target was not found.
```

I was trying to fix the problem by adding

**find_package(Qt5 COMPONENTS Widgets Core REQUIRED)**
in  UI/frontend-plugins/source-dock/CMakeLists.txt
And I got another error,

```
1757/1911] Swig compile obspython.i for python
Deprecated command line option: -py3. Ignored, this option is no longer supported.
ninja: build stopped: subcommand failed.
+ ERROR during build step: configure build
```
Still failed.

Any one can help me to build the source-dock successfully.

 

Environment:
OBS: master branch
QT: QT 5.15
OS: MacOS 12.4 Monterey

**Comment by exeldro** [comment]
I think the CMakeLists.txt might need this added:
`find_package(Qt5Widgets)`

**Comment by jonahjunwu** [comment]
I got same failed result.

## code
```
project(source-dock VERSION 0.3.2)
set(PROJECT_FULL_NAME "Source Dock")
find_package(Qt5Widgets)
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/version.h.in ${CMAKE_CURRENT_SOURCE_DIR}/version.h)
```

## same result
```
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for SourceDockSettingsDialog", referenced from:
      SourceDockSettingsDialog::SourceDockSettingsDialog(QMainWindow*) in source-dock-settings.cpp.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1757/1911] Swig compile obspython.i for python
Deprecated command line option: -py3. Ignored, this option is no longer supported.
ninja: build stopped: subcommand failed.
  + ERROR during build step: configure build
```
